name: build
on: [push]
jobs:
  build:
    strategy:
      matrix:
        version: [1.24]
        os: [ubuntu-latest]
    name: Build
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.version }}
      id: go

    - name: checkout
      uses: actions/checkout@v5

    - name: build
      run: go build

  
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v6
        with:
          go-version: 1.24
      - uses: actions/checkout@v5
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
